export type WorkflowStep = 'diagnosis' | 'plan' | 'resources' | 'execution' | 'validation' | 'summary';
export type ActionCategory =
  | 'Hardware'
  | 'Software'
  | 'Configuration'
  | 'Network'
  | 'Maintenance'
  | 'Inspection'
  | 'Power'
  | 'Security'
  | 'Storage'
  | 'Peripheral'
  | 'Performance'
  | 'Thermal'
  | 'Consumables'
  | 'Firmware'
  | 'Cabling';

export type ActionStatus = 'Planned' | 'In Progress' | 'Done';

export const ACTION_TYPES_BY_CATEGORY: Record<ActionCategory, string[]> = {
  'Hardware': ['Install', 'Replace', 'Repair', 'Clean', 'Upgrade', 'Remove', 'Test'],
  'Software': ['Install', 'Uninstall', 'Update', 'Configure', 'Repair', 'Rollback', 'License'],
  'Configuration': ['Modify', 'Reset', 'Backup', 'Restore', 'Optimize', 'Audit'],
  'Network': ['Configure', 'Test', 'Troubleshoot', 'Reset', 'Monitor', 'Update Firmware'],
  'Maintenance': ['Clean', 'Inspect', 'Lubricate', 'Replace Consumable', 'Calibrate', 'Preventive Check'],
  'Inspection': ['Visual Check', 'Performance Test', 'Stress Test', 'Log Review', 'Thermal Check'],
  'Power': ['Replace Battery', 'Replace PSU', 'Test Voltage', 'Configure UPS', 'Clean Power Port'],
  'Security': ['Virus Scan', 'Firewall Config', 'Update Definitions', 'Audit Access', 'Reset Credentials'],
  'Storage': ['Format Drive', 'Partition', 'Data Recovery', 'Wipe Drive', 'Expand Volume'],
  'Peripheral': ['Install Driver', 'Replace Cable', 'Calibrate', 'Clean Port', 'Test Connectivity'],
  'Performance': ['Optimization', 'Resource Audit', 'Defragment', 'Clean Registry', 'Overclock/Underclock'],
  'Thermal': ['Apply Thermal Paste', 'Clean Fan', 'Replace Fan', 'Heatsink Mod', 'Temperature Audit'],
  'Consumables': ['Replace Toner', 'Refill Fluid', 'Replace Filter', 'Apply Lubricant', 'Replace Battery'],
  'Firmware': ['Update BIOS', 'Flash Firmware', 'Reset NVRAM', 'Verify Checksum', 'Rollback Version'],
  'Cabling': ['Reroute Cables', 'Replace Connector', 'Label Cables', 'Test Continuity', 'Organize Rack']
};

export const CATEGORY_ICONS: Record<ActionCategory, string> = {
  'Hardware': '🔧',
  'Software': '💻',
  'Configuration': '⚙️',
  'Network': '🌐',
  'Maintenance': '🧹',
  'Inspection': '🔍',
  'Power': '⚡',
  'Security': '🛡️',
  'Storage': '💾',
  'Peripheral': '🔌',
  'Performance': '🚀',
  'Thermal': '🌡️',
  'Consumables': '📦',
  'Firmware': '💾',
  'Cabling': '🧵'
};

export interface WorkbenchAction {
  id: string;
  category: ActionCategory;
  type: string;
  target: string;
  description: string;
  status: ActionStatus;
  notes: string;
  resources: WorkbenchResource[];
  expandedInExecution?: boolean;
  isCollapsed?: boolean;

  priority?: 'High' | 'Medium' | 'Low';
  estimatedTime?: string;
  timeSpent?: number; // seconds
  isAiGenerated?: boolean;
}

export interface WorkbenchResource {
  resourceType: 'part' | 'software' | 'config' | 'network' | 'firmware' | 'service';
  name: string;
  quantity?: number;
  value?: string;
  specification?: string;
  equipmentId?: string;     // inventory item ID — used for lifecycle update on completion
  replacesSpecKey?: string; // spec key this part replaces (e.g. "RAM", "Storage")
}

export interface ValidationItem {
  label: string;
  status: 'pending' | 'success' | 'failed';
  failureReason?: string;
  autoGenerated: boolean;
}

export interface WorkbenchTimelineEntry {
  title: string;
  icon: string;
  color: string;
  time: string;
}

export interface WorkbenchState {
  ticketId: string;
  currentStep: WorkflowStep;
  manualDiagnosis: string;
  diagnosisResult: string;
  diagnosisCategories: string[];
  diagnosisSymptoms: string[];
  additionalNotes: string;
  actions: WorkbenchAction[];
  validationChecklist: ValidationItem[];
  validationNotes: string;
  summaryNote: string;
  globalNotes: string;
  timeline: WorkbenchTimelineEntry[];
  startedAt: string;

  actionStartTimes?: Record<string, string>; // actionId -> ISO date string when timer started

  // AI Persistence
  aiDiagnosisCauses?: string[];
  aiDiagnosisChecks?: string[];
  aiPredictiveMap?: any[];
  aiSimilarCase?: any;
  lastAiDiagnosisInput?: string | null;
  lastAiPredictiveInput?: string | null;

  // Plan & Resources Persistence
  lastGeneratedDiagnosis?: string | null;
  aiResourceMatched?: boolean;
  aiTestsGenerated?: boolean;
  aiPlanGenerated?: boolean;
}

export interface CapabilityResponse {
  equipmentType: string;
  categories: string[];
  categoryTypes: { [category: string]: string[] };
  categoryTargets: { [category: string]: string[] };
}
