package com.example.usermicroservice.model;

public enum AlertType {
    LOW_STOCK,
    OUT_OF_STOCK,
    REQUEST_PENDING,
    TICKET_OVERDUE,
    TICKET_CANCELLED,
    WARRANTY_EXPIRING,
    WARRANTY_EXPIRED,
    SHELF_EMPTY,
    LICENSE_DEPLETED,
    LICENSE_POOL_DEPLETED,
    LICENSE_POOL_EXPIRED,
    TASK_OVERDUE,
    SYSTEM
}
