spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@localhost:27017/userdb?authSource=admin}
server.port=8080

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mejrissiahmed4432@gmail.com
spring.mail.password=gnhdqdbxlztxflwp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
